In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#using pre-train model w2v
print("K-Means")
from gensim.models import KeyedVectors 
from distutils.version import LooseVersion, StrictVersion
import gensim 
import gensim.models.keyedvectors as word2vec
#w2v_model = word2vec.KeyedVectors.load('w2v.model')
model = '/content/drive/MyDrive/baomoi.window2.vn.model.bin'
if LooseVersion(gensim.__version__) >= LooseVersion("1.0.1"):
    w2v_model = KeyedVectors.load_word2vec_format(model, binary=True)
else:
    w2v_model = Word2Vec.load_word2vec_format(model, binary=True)
vocabulary = []
for word in w2v_model.vocab.keys():
    vocabulary.append(word)
print(len(vocabulary))

K-Means
439056


In [ ]:
# using model w2v train again with data VNTC
# print("K-Means")
# from gensim.models import KeyedVectors 
# from distutils.version import LooseVersion, StrictVersion
# import gensim 
# import gensim.models.keyedvectors as word2vec
# w2v_model = word2vec.KeyedVectors.load('/content/drive/MyDrive/text summarization /vietnamese-text-summarization-master/sources/model/w2v_sen1.model')

# vocabulary = []
# for word in w2v_model.vocab.keys():
#     vocabulary.append(word)
# print(len(vocabulary))

K-Means
146759


In [ ]:
content = """
Trump cáo buộc đảng Dân chủ đang theo đuổi "nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" khi tìm cách luận tội ông.

"Chính các người mới là phe can thiệp vào bầu cử Mỹ, phá vỡ nền dân chủ của đất nước và cản trở công lý. Điều này không là gì khác ngoài một nỗ lực đảo chính bất hợp pháp, mang tính đảng phái và sẽ thất bại nặng nề tại hòm phiếu, dựa trên tình hình gần đây", Tổng thống Mỹ Donald Trump viết trong lá thư dài 6 trang gửi Chủ tịch Hạ viện Nancy Pelosi vào hôm qua để chỉ trích cuộc điều tra luận tội của phe Dân chủ. 

Ông chủ Nhà Trắng viết thêm rằng bà Pelosi "đang biến hạ viện từ cơ quan lập pháp được kính trọng thành một phòng xử án của cuộc đàn áp đảng phái", đồng thời "gần như không thèm che giấu sự thù ghét" đối với ông. 

"Bằng cách thúc đẩy cuộc luận tội trái phép đó, các người đang vi phạm lời thề nhậm chức, phá vỡ lòng trung thành với hiến pháp và tuyên chiến với nền dân chủ Mỹ. Các người coi dân chủ là kẻ thù của chính mình", Trump viết.
Bức thư của Trump được gửi đi trong bối cảnh hạ viện, nơi đảng Dân chủ chiếm đa số, dự kiến bỏ phiếu vào hôm nay về các điều khoản luận tội Tổng thống Mỹ và khả năng cao sẽ thông qua để đưa Trump ra xét xử tại thượng viện. Ông gần như chắc chắn sẽ trở thành tổng thống Mỹ thứ ba trong lịch sử bị luận tội. 

Trước đó, Ủy ban Tư pháp Hạ viện đã thông qua hai điều khoản luận tội Trump, bao gồm lạm dụng quyền lực và cản trở quốc hội. Phe Dân chủ cáo buộc Trump thúc ép Ukraine điều tra cha con cựu phó tổng thống Mỹ Joe Biden, đối thủ của Trump trong cuộc bầu cử năm 2020, gây nguy hiểm cho hiến pháp Mỹ, an ninh quốc gia và tính công bằng của bầu cử. 

Trong khi đó, đảng Cộng hòa vẫn cố gắng bảo vệ Trump, khi lãnh đạo phe đa số tại thượng viện Mitch McConnell bác bỏ yêu cầu của đảng Dân chủ nhằm đề nghị 4 quan chức cũ và đương nhiệm ra làm chứng tại phiên tòa luận tội dự kiến diễn ra ở thượng viện vào tháng tới. 

Hạ viện Mỹ mở cuộc điều tra luận tội Trump từ tháng 9, sau khi một người tố giác giấu tên đệ đơn cáo buộc Tổng thống Mỹ dùng gói viện trợ quân sự để gây áp lực lên người đồng cấp Ukraine Volodymyr Zelensky. Tuy nhiên, Trump phủ nhận các cáo buộc và gọi cuộc điều tra luận tội là trò lừa bịp.
"""
# content = """
# iPhone Pro 11 Max đang chạy hệ điều hành iOS 13 mới nhất của Apple. Về hiệu năng, iPhone 11 Pro Max là iPhone mạnh nhất hiện nay. Điểm Geekbench của iPhone 11 Pro Max là 3420, con số này thể hiện rằng 11 Pro Max mạnh hơn khoảng 10% so với iPhone 11 và hơn 20% so với iPhone XS Max.
# Nhưng đây chỉ là những con số, còn hiệu năng thực tế của iPhone 11 Pro Max khi sử dụng hàng ngày thì sao? Thật khó để có thể khiến iPhone chậm đi, bởi vì máy có tốc độ khởi động ứng dụng rất nhanh và bạn có thể sử dụng chúng ngay lập tức.
# Tuy nhiên, camera là ứng dụng duy nhất iPhone thể hiện sự chậm chạp, phải mất một giây để tải ứng dụng (đôi khi nó có thể bị đứng). Khi bạn chụp ảnh bằng ống kính siêu rộng xem, hình ảnh cũng không xuất hiện ngay lập tức khi nhấn nút chụp.
# Tải ảnh để chỉnh sửa cũng mất một hoặc hai giây, cũng như một số thao tác lưu hình ảnh. Chúng tôi đánh giá cao việc iPhone có thể chịu được một lượng lớn hình ảnh được xử lý. Tuy nhiên, chúng tôi mong đợi mọi thứ sẽ nhanh hơn một chút, thay vì phải để xem một bánh xe quay quay trong quá trình xử lý. Thêm nữa, khi xem một bộ phim được tải về và tua đến một cảnh tùy ý thì iPhone lại bị đứng.
# Mỗi năm một lần, hội rước đèn đêm Trung thu ở xã em diễn ra tại sân vận động của xã rất từng bừng, náo nhiệt.
# Tối mười bốn tháng tám âm lịch, trên bãi sân rộng, thiếu nhi trong xã xếp hàng từng đội theo xóm. Tay bạn nào cũng cầm theo một cái lồng đèn được mua hoặc tự làm hay ống tre làm thành đuốc. Ban tổ chức gọi tổ trưởng lên bàn nhận bánh kẹo về cho tổ mình. Sau khi tổ trưởng phát xong kẹo bánh, có vài tiết mục văn nghệ “Cây nhà lá vườn” diễn ra ở sân rộng, thiếu niên nhi đồng vỗ tay theo nhịp, ủng hộ những nghệ sĩ không chuyên nghiệp của xã nhà. Tiếp đó là lệnh đốt nến. Tất cả các lồng đèn, đuốc được thắp sáng. Lúc bấy giờ sân bãi đẹp lung linh, kì ảo với hàng trăm ánh nến xanh, vàng, đỏ và ánh hồng của cây đuốc làm bằng ống tre. Lễ rước đèn Trung thu bắt đầu bằng bài hát “Rước đèn Trung thu”. Thiếu nhi vừa cầm lồng đèn, vừa hát “Tết Trung thu...”. Đoàn rước đèn đi một vòng quanh xã. Các cô chú Đội sản xuất và các anh chị Thanh niên xã đoàn đi kèm thiếu nhi đều giữ hàng ngũ ngay ngắn, trật tự, vừa tạo mĩ quan của hội rước đèn, vừa coi sóc phòng cháy (do đốt đèn nến và đuốc nên phải tăng cường phòng vệ, trông coi). Dọc đường, có bạn cầm lồng đèn từ trong nhà chạy ra nhập vào đoàn thiếu nhi đang “rồng rắn” rước đèn. Trên đường về, bạn nàonhà gần đường đi rước đèn có thể tách hàng về nhà. Trăng lúc này đã lên cao, tròn vành vạnh soi ánh vàng trong trẻo xuống mặt đất. Đoàn thiếu nhi vừa đi, vừa hát trở lại chỗ xuất phát. Các anh chị xã đoàn bắt nhịp bài hát "Như có Bác trong ngày đại thắng”. Kết thúc ngày hội, chúng em chia tay nhau và ra về.
# Buổi lễ rước đèn là sinh hoạt rất vui của thiếu nhi xã em và đã trở thành thông lệ không thể thiếu trong ngày lễ Trung Thu. Em rất yêu quê và yêu ngày hội Trung thu ở quê hương mình.
# """
contents_parsed = content.lower() 
contents_parsed = contents_parsed.replace('\n', ' ')
contents_parsed = contents_parsed.strip() 

import nltk
nltk.download('punkt')
sentences = nltk.sent_tokenize(contents_parsed)

i = 0
for sentence in sentences:
    print(i,"===", sentence)
    i += 1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
0 === trump cáo buộc đảng dân chủ đang theo đuổi "nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" khi tìm cách luận tội ông.
1 === "chính các người mới là phe can thiệp vào bầu cử mỹ, phá vỡ nền dân chủ của đất nước và cản trở công lý.
2 === điều này không là gì khác ngoài một nỗ lực đảo chính bất hợp pháp, mang tính đảng phái và sẽ thất bại nặng nề tại hòm phiếu, dựa trên tình hình gần đây", tổng thống mỹ donald trump viết trong lá thư dài 6 trang gửi chủ tịch hạ viện nancy pelosi vào hôm qua để chỉ trích cuộc điều tra luận tội của phe dân chủ.
3 === ông chủ nhà trắng viết thêm rằng bà pelosi "đang biến hạ viện từ cơ quan lập pháp được kính trọng thành một phòng xử án của cuộc đàn áp đảng phái", đồng thời "gần như không thèm che giấu sự thù ghét" đối với ông.
4 === "bằng cách thúc đẩy cuộc luận tội trái phép đó, các người đang vi phạm lời thề nhậm chức, phá vỡ lòng trung 

In [ ]:
!pip install pyvi

with pre-train model w2v using vector 300 

with model w2v train again using vector 128

In [ ]:
from pyvi import ViTokenizer
import numpy as np 

X = []
for sentence in sentences:
    
    # sentence = gensim.utils.simple_preprocess(sentence)
    # sentence = ' '.join(sentence)
    sentence_tokenized = ViTokenizer.tokenize(sentence)
    # print(sentence_tokenized)
    words = sentence_tokenized.split(" ")
    sentence_vec = np.zeros((300))
    for word in words:
        if word in vocabulary:
            sentence_vec+=w2v_model[word]
    X.append(sentence_vec)

print(len(X))

13


In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min

n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters)
kmeans = kmeans.fit(X)

print("K-Means Clustering\n")
avg = []
for j in range(n_clusters):
    print("Cụm", j+1)
    idx = np.where(kmeans.labels_ == j)[0] 
    print(idx)
    avg.append(np.mean(idx))
    print("Thứ tự trung bình: ", round(np.mean(idx), 2))
    print("="*115)
closest, _ = pairwise_distances_argmin_min(kmeans.cluster_centers_, X)
print("Các câu gần", n_clusters, "tâm cụm nhất",closest)
ordering = sorted(range(n_clusters), key=lambda k: avg[k])
# print(ordering)
print("\nKết quả tóm tắt:\n")
summary = ' '.join(["(Câu " + str(closest[idx]) + ") " + sentences[closest[idx]] for idx in ordering])
print(summary)

K-Means Clustering

Cụm 1
[ 2  6 10]
Thứ tự trung bình:  6.0
Cụm 2
[ 0  1  3  4  5  7  8 11 12]
Thứ tự trung bình:  5.67
Cụm 3
[9]
Thứ tự trung bình:  9.0
Các câu gần 3 tâm cụm nhất [6 0 9]

Kết quả tóm tắt:

(Câu 0) trump cáo buộc đảng dân chủ đang theo đuổi "nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" khi tìm cách luận tội ông. (Câu 6) bức thư của trump được gửi đi trong bối cảnh hạ viện, nơi đảng dân chủ chiếm đa số, dự kiến bỏ phiếu vào hôm nay về các điều khoản luận tội tổng thống mỹ và khả năng cao sẽ thông qua để đưa trump ra xét xử tại thượng viện. (Câu 9) phe dân chủ cáo buộc trump thúc ép ukraine điều tra cha con cựu phó tổng thống mỹ joe biden, đối thủ của trump trong cuộc bầu cử năm 2020, gây nguy hiểm cho hiến pháp mỹ, an ninh quốc gia và tính công bằng của bầu cử.


In [ ]:
print(np.where(kmeans.labels_ == j))

(array([ 9, 11]),)


In [ ]:
#model word2vec 
(Câu 0) trump cáo buộc đảng dân chủ đang theo đuổi 
"nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" 
khi tìm cách luận tội ông.
(Câu 6) bức thư của trump được gửi đi trong bối cảnh hạ viện, 
nơi đảng dân chủ chiếm đa số, dự kiến bỏ phiếu vào hôm nay về các 
điều khoản luận tội tổng thống mỹ và khả năng cao sẽ thông
qua để đưa trump ra xét xử tại thượng viện. 
(Câu 11) hạ viện mỹ mở cuộc điều tra luận tội trump từ tháng 9,
sau khi một người tố giác giấu tên đệ đơn cáo buộc tổng
thống mỹ dùng gói viện trợ quân sự để gây áp lực 
lên người đồng cấp ukraine volodymyr zelensky.

In [ ]:
#pre-train model word2vec
(Câu 5) các người coi dân chủ là kẻ thù của chính mình", trump viết.
(Câu 6) bức thư của trump được gửi đi trong bối cảnh hạ viện, nơi
đảng dân chủ chiếm đa số, dự kiến bỏ phiếu vào hôm nay về các điều 
khoản luận tội tổng thống mỹ và khả năng cao sẽ thông qua để đưa 
trump ra xét xử tại thượng viện. 
(Câu 8) trước đó, ủy ban tư pháp hạ viện đã thôngqua hai điều khoản 
luận tội trump, bao gồm lạm dụng quyền lực và cản trở quốc hội.